apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-nfs-pv
  labels:
    {{- include "questions.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - proto=tcp
    - port=2049
  nfs:
    path: /mnt
    server: 192.168.1.157

