questions:
  image-dir: ${IMAGE_DIR}
  connect-timeout: 3000
  read-timeout: 30000

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${QUESTIONS_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 300000 #5 minutes wait time
  jpa:
    hibernate:
      ddl-auto: update
