questions:
  gs-decryptor-enabled: ${GS_DECRYPTOR_ENABLED}
  secret-key: ${GS_SECRET_KEY}
  init-vector: ${GS_INIT_VECTOR}
  db-location: ${GS_DB_LOCATION}
  content-source-location: ${CONTENT_SOURCE_LOCATION}
  image-dir: ${IMAGE_DIR}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${QUESTIONS_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 300000 #5 minutes wait time
  jpa:
    hibernate:
      ddl-auto: update
